# Generated by Django 3.1.7 on 2021-10-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChName', models.CharField(max_length=50, verbose_name='Chart Name')),
                ('TotalGra', models.IntegerField(default=0, verbose_name='total student')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Convocation Name')),
                ('photo', models.ImageField(blank=True, upload_to='ConvocationLogo/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=500, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=500, null=True)),
                ('issandbox', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PaymentGatewaySetting',
                'verbose_name_plural': 'PaymentGatewaySettings',
                'db_table': 'paymentgatewaysettings',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Slider Name')),
                ('photo', models.ImageField(blank=True, upload_to='Slider/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_usename', models.CharField(default='', max_length=50, verbose_name='Degree')),
                ('s_id', models.IntegerField(default=0, unique=True, verbose_name='Student ID')),
                ('intake', models.IntegerField(verbose_name='Intake')),
                ('std_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('Cell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('totalMejor', models.IntegerField(blank=True, default=0, verbose_name='Total Major')),
                ('paidFor', models.IntegerField(blank=True, default=0, verbose_name='Paid For Major')),
                ('hasPaid', models.BooleanField(default=False, verbose_name='Payment Done')),
                ('regDate', models.DateField(auto_now=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sid', models.IntegerField(default=0, unique=True, verbose_name='Student ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_id', models.CharField(max_length=15)),
                ('val_id', models.CharField(max_length=75)),
                ('card_type', models.CharField(max_length=150)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(max_length=55, null=True)),
                ('bank_tran_id', models.CharField(max_length=155, null=True)),
                ('status', models.CharField(max_length=55)),
                ('tran_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('card_issuer', models.CharField(max_length=255)),
                ('card_brand', models.CharField(max_length=15)),
                ('card_issuer_country', models.CharField(max_length=55)),
                ('card_issuer_country_code', models.CharField(max_length=55)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verify_sign', models.CharField(max_length=155)),
                ('verify_sign_sha2', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=15)),
                ('risk_title', models.CharField(max_length=25)),
            ],
        ),
    ]
