# Generated by Django 3.1.7 on 2021-10-26 15:54

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChName', models.CharField(max_length=50, verbose_name='Chart Name')),
                ('TotalGra', models.IntegerField(default=0, verbose_name='total student')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, unique=True)),
                ('lstOrder', models.CharField(default='', max_length=3, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Program Committee',
                'verbose_name_plural': 'Program Committees',
                'ordering': ['-lstOrder'],
            },
        ),
        migrations.CreateModel(
            name='ConvocationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, unique=True)),
                ('lstOrder', models.CharField(default='', max_length=3, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Previous Convocation',
                'verbose_name_plural': 'Previous Convocations',
                'ordering': ['-lstOrder'],
            },
        ),
        migrations.CreateModel(
            name='ConvocationLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Convocation Name')),
                ('photo', models.ImageField(blank=True, upload_to='ConvocationLogo/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Goldmadelists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_Name', models.CharField(max_length=50, verbose_name='Goldmadelist Name')),
                ('Program', models.CharField(max_length=50, verbose_name='Student Program')),
                ('intake', models.IntegerField(default=0, verbose_name='Student intake')),
                ('section', models.IntegerField(default=0, verbose_name='Student intake')),
                ('photo', models.ImageField(blank=True, upload_to='GOldmadelist/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Message/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(blank=True, max_length=500, null=True)),
                ('store_pass', models.CharField(blank=True, max_length=500, null=True)),
                ('issandbox', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PaymentGatewaySetting',
                'verbose_name_plural': 'PaymentGatewaySettings',
                'db_table': 'paymentgatewaysettings',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(default=0, unique=True, verbose_name='Student ID')),
                ('stu_name', models.CharField(default='', max_length=40)),
                ('father_name', models.CharField(default='', max_length=40)),
                ('mother_name', models.CharField(default='', max_length=40)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(default='', max_length=40)),
                ('tran_id', models.CharField(max_length=15)),
                ('tran_date', models.DateTimeField()),
                ('Cell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Phone')),
                ('secondCell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Others Phone')),
                ('totalDegree', models.IntegerField(blank=True, default=0, verbose_name='Total Degree')),
                ('firstDegree', models.CharField(default='', max_length=50, verbose_name='First Degree')),
                ('secondDegree', models.CharField(default='', max_length=50, verbose_name='Second Degree')),
                ('secondDegree_id', models.IntegerField(default=0, unique=True, verbose_name='Second Degree ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Rules/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Schedule Name')),
                ('photo', models.ImageField(blank=True, upload_to='Schedule/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Speech/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_usename', models.CharField(default='', max_length=50, verbose_name='Degree')),
                ('s_id', models.IntegerField(default=0, unique=True, verbose_name='Student ID')),
                ('intake', models.IntegerField(verbose_name='Intake')),
                ('std_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('Cell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('totalMejor', models.IntegerField(blank=True, default=0, verbose_name='Total Major')),
                ('paidFor', models.IntegerField(blank=True, default=0, verbose_name='Paid For Major')),
                ('tranId', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Transction ID')),
                ('hasPaid', models.BooleanField(default=False, verbose_name='Payment Done')),
                ('isRegDone', models.BooleanField(default=False, verbose_name='Registration Done')),
                ('regDate', models.DateField(auto_now=True, verbose_name='Registration Date')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sid', models.IntegerField(default=0, unique=True, verbose_name='Student ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_id', models.CharField(max_length=15, unique=True)),
                ('val_id', models.CharField(max_length=75)),
                ('card_type', models.CharField(max_length=150)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(max_length=55, null=True)),
                ('bank_tran_id', models.CharField(max_length=155, null=True)),
                ('status', models.CharField(max_length=55)),
                ('tran_date', models.DateTimeField(auto_now=True, verbose_name='Transaction Date')),
                ('currency', models.CharField(max_length=10)),
                ('card_issuer', models.CharField(max_length=255)),
                ('card_brand', models.CharField(max_length=15)),
                ('card_issuer_country', models.CharField(max_length=55)),
                ('card_issuer_country_code', models.CharField(max_length=55)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verify_sign', models.CharField(max_length=155)),
                ('verify_sign_sha2', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=15)),
                ('risk_title', models.CharField(max_length=25)),
                ('email', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Venu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Venu/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('convocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Slider Name')),
                ('photo', models.ImageField(blank=True, upload_to='Slider/')),
                ('guest', models.CharField(default='', max_length=50, verbose_name='Guest Name')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('convocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList')),
            ],
        ),
        migrations.CreateModel(
            name='ProSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Venu/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('convocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList')),
            ],
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Gallary/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('convocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList')),
            ],
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Convocation Name')),
                ('photo', models.ImageField(blank=True, upload_to='ConvocationLogo/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('convocation', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='Committee/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
                ('committeelist', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.committeelist', verbose_name='Committee List')),
            ],
        ),
    ]
