# Generated by Django 3.1.7 on 2021-10-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.IntegerField(max_length=11, unique=True, verbose_name='Student ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('phone', models.IntegerField(blank=True, unique=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email')),
                ('totalMejor', models.IntegerField(blank=True, max_length=1, verbose_name='Total Major')),
                ('paidFor', models.IntegerField(blank=True, max_length=1, verbose_name='Paid For Major')),
                ('hasPaid', models.BooleanField(default=False, verbose_name='Payment Done')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.degree', verbose_name='Degree')),
                ('intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.intake', verbose_name='Intake')),
            ],
        ),
    ]
