# Generated by Django 3.2 on 2021-10-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateTimeField(auto_now=True, verbose_name='Dath Of Birth'),
        ),
    ]
