# Generated by Django 3.1.7 on 2021-10-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='Cell_Phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='emai',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='degree',
            new_name='p_usename',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='std_full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='studentID',
        ),
        migrations.AddField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(default=1, max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='Student ID'),
            preserve_default=False,
        ),
    ]
