# Generated by Django 3.2.8 on 2021-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hosturl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liveSiteUrl', models.CharField(max_length=100)),
                ('testSiteUrl', models.CharField(max_length=100)),
                ('localhost', models.CharField(max_length=50)),
                ('isLive', models.BooleanField(default=False)),
                ('isTest', models.BooleanField(default=False)),
                ('isLocal', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='firstDegree_id',
            field=models.IntegerField(default=0, verbose_name='First Degree ID'),
        ),
    ]
