# Generated by Django 3.2 on 2021-10-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211027_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='title',
        ),
        migrations.AlterField(
            model_name='mail',
            name='email',
            field=models.EmailField(default='', max_length=150),
        ),
    ]
