# Generated by Django 3.2.8 on 2021-10-28 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211028_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosturl',
            old_name='liveSiteUrl',
            new_name='siteUrl',
        ),
        migrations.RemoveField(
            model_name='hosturl',
            name='isLive',
        ),
        migrations.RemoveField(
            model_name='hosturl',
            name='isLocal',
        ),
        migrations.RemoveField(
            model_name='hosturl',
            name='isTest',
        ),
        migrations.RemoveField(
            model_name='hosturl',
            name='localhost',
        ),
        migrations.RemoveField(
            model_name='hosturl',
            name='testSiteUrl',
        ),
    ]
