# Generated by Django 3.1.7 on 2021-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211023_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goldmadelists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_Name', models.CharField(max_length=50, verbose_name='Goldmadelist Name')),
                ('Program', models.CharField(max_length=50, verbose_name='Student Program')),
                ('intake', models.IntegerField(default=0, verbose_name='Student intake')),
                ('section', models.IntegerField(default=0, verbose_name='Student intake')),
                ('photo', models.ImageField(blank=True, upload_to='GOldmadelist/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
    ]
