# Generated by Django 3.2 on 2021-10-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tranId',
            field=models.CharField(default='', max_length=100, verbose_name='Transction ID'),
        ),
    ]
