# Generated by Django 3.1.7 on 2021-10-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211020_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regDate',
            field=models.DateField(auto_now=True),
        ),
    ]
