# Generated by Django 3.1.6 on 2021-10-24 06:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_goldmadelists'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, unique=True)),
                ('lstOrder', models.CharField(default='', max_length=3, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Program Committee',
                'verbose_name_plural': 'Program Committees',
                'ordering': ['-lstOrder'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Schedule Name')),
                ('photo', models.ImageField(blank=True, upload_to='Schedule/')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='committee',
            name='committeelist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.committeelist', verbose_name='Committee List'),
        ),
    ]
