# Generated by Django 3.2.8 on 2021-10-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211028_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officemail',
            name='email',
        ),
        migrations.AddField(
            model_name='officemail',
            name='accounceOfficeEmail',
            field=models.CharField(default='', max_length=150, verbose_name='Accounce Email'),
        ),
        migrations.AddField(
            model_name='officemail',
            name='officeEmail1',
            field=models.CharField(default='', max_length=150, verbose_name='Other office email 1'),
        ),
        migrations.AddField(
            model_name='officemail',
            name='officeEmail2',
            field=models.CharField(default='', max_length=150, verbose_name='Other office email 2'),
        ),
        migrations.AddField(
            model_name='officemail',
            name='officeEmail3',
            field=models.CharField(default='', max_length=150, verbose_name='Other office email 3'),
        ),
        migrations.AddField(
            model_name='officemail',
            name='regOfficeEmail',
            field=models.CharField(default='', max_length=150, verbose_name='Reg Office Email'),
        ),
    ]
