# Generated by Django 3.2 on 2021-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_mail_officemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tranId',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Transction ID'),
        ),
    ]
