# Generated by Django 3.1.7 on 2021-10-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_regdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='intake',
            field=models.IntegerField(null=True, verbose_name='Intake'),
        ),
        migrations.AlterField(
            model_name='student',
            name='p_usename',
            field=models.CharField(max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paidFor',
            field=models.IntegerField(blank=True, verbose_name='Paid For Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='totalMejor',
            field=models.IntegerField(blank=True, verbose_name='Total Major'),
        ),
    ]
