# Generated by Django 3.2 on 2021-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='OfficeMail',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
                migrations.AlterField(
            model_name='student',
            name='tranId',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Transction ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='Transaction ID'),
        ),
    
        migrations.AlterField(
            model_name='student',
            name='totalPaid',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Paid'),
        ),
    ]
