# Generated by Django 3.2 on 2021-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='OfficeMail',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
    ]
