# Generated by Django 3.2.8 on 2021-10-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211028_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='officemail',
            name='officeEmail4',
            field=models.CharField(default='', max_length=150, verbose_name='Other office email 4'),
        ),
    ]
