# Generated by Django 3.1.6 on 2021-10-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211024_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallary',
            name='convocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList'),
        ),
    ]
