# Generated by Django 3.2.8 on 2021-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_officemail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='totalPaid',
            field=models.IntegerField(default=0, verbose_name='Total Paid'),
        ),
    ]
