# Generated by Django 3.1.6 on 2021-10-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_gallary_convocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='proschrdule',
            name='convocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList'),
        ),
        migrations.AddField(
            model_name='venu',
            name='convocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList'),
        ),
        migrations.AlterField(
            model_name='convocation',
            name='convocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList'),
        ),
    ]
