# Generated by Django 3.2 on 2021-10-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_tranid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tranId',
            field=models.CharField(default='', max_length=100, verbose_name='Transction ID'),
        ),
    ]
