# Generated by Django 3.1.6 on 2021-10-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211024_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProSchrdule',
            new_name='ProSchedule',
        ),
    ]
