# Generated by Django 3.1.7 on 2021-10-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211020_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Cell_Phone',
            field=models.IntegerField(blank=True, default=0, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emai',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='intake',
            field=models.IntegerField(verbose_name='Intake'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paidFor',
            field=models.IntegerField(blank=True, default=0, verbose_name='Paid For Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_full_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='totalMejor',
            field=models.IntegerField(blank=True, default=0, verbose_name='Total Major'),
        ),
    ]
