# Generated by Django 3.1.7 on 2021-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211020_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regDate',
            field=models.DateField(auto_now=True, verbose_name='Registration Date'),
        ),
    ]
