# Generated by Django 3.1.7 on 2021-10-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211027_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tranId',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Transction ID'),
        ),
    ]
