# Generated by Django 3.2.8 on 2021-10-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isRegDone',
            field=models.BooleanField(default=False, verbose_name='Payment Done'),
        ),
    ]
