# Generated by Django 3.1.7 on 2021-10-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211020_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Cell_Phone',
            field=models.IntegerField(blank=True, default=0, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emai',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
    ]
