# Generated by Django 3.1.7 on 2021-10-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_transaction_cellphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='degree_2_id',
            field=models.CharField(default='', max_length=11, verbose_name='Degree 2 ID'),
        ),
    ]
