# Generated by Django 3.1.7 on 2021-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211027_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Cell_Phone',
            field=models.IntegerField(default=0, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='secondCell_Phone',
            field=models.IntegerField(default=0, verbose_name='Others Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='secondDegree_id',
            field=models.IntegerField(default=0, verbose_name='Second Degree ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='stu_id',
            field=models.IntegerField(default=0, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='totalDegree',
            field=models.IntegerField(blank=True, verbose_name='Total Degree'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tran_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Cell_Phone',
            field=models.IntegerField(verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hasPaid',
            field=models.BooleanField(verbose_name='Payment Done'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isRegDone',
            field=models.BooleanField(verbose_name='Registration Done'),
        ),
        migrations.AlterField(
            model_name='student',
            name='p_usename',
            field=models.CharField(max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paidFor',
            field=models.IntegerField(default=0, verbose_name='Paid For Major'),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_id',
            field=models.IntegerField(verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='totalMejor',
            field=models.IntegerField(default=0, verbose_name='Total Major'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sid',
            field=models.IntegerField(default=0, verbose_name='Student ID'),
        ),
    ]
