# Generated by Django 3.1.7 on 2021-10-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211020_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChName', models.CharField(max_length=50, verbose_name='Chart Name')),
                ('TotalGra', models.IntegerField(default=0, verbose_name='total student')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ConvocationLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Convocation Name')),
                ('photo', models.ImageField(blank=True, upload_to='ConvocationLogo/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Slider Name')),
                ('photo', models.ImageField(blank=True, upload_to='Slider/')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='emai',
            new_name='email',
        ),
    ]
