# Generated by Django 3.1.7 on 2021-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211027_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='secondCell_Phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='stu_id',
        ),
        migrations.AddField(
            model_name='registration',
            name='firstDegree_id',
            field=models.IntegerField(default=0, verbose_name='Second Degree ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='stu_id1',
            field=models.IntegerField(default=0, verbose_name='Student ID 1'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='totalDegree',
            field=models.IntegerField(default=1, verbose_name='Total Degree'),
        ),
    ]
