# Generated by Django 3.2 on 2021-10-26 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_isregdone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(default=0, unique=True, verbose_name='Student ID')),
                ('stu_name', models.CharField(default='', max_length=40)),
                ('father_name', models.CharField(default='', max_length=40)),
                ('mother_name', models.CharField(default='', max_length=40)),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(default='', max_length=40)),
                ('tran_id', models.CharField(max_length=15)),
                ('tran_date', models.DateTimeField()),
                ('Cell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Phone')),
                ('secondCell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Others Phone')),
                ('totalDegree', models.IntegerField(blank=True, default=0, verbose_name='Total Degree')),
                ('firstDegree', models.CharField(default='', max_length=50, verbose_name='First Degree')),
                ('secondDegree', models.CharField(default='', max_length=50, verbose_name='Second Degree')),
                ('secondDegree_id', models.IntegerField(default=0, unique=True, verbose_name='Second Degree ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='isRegDone',
        ),
        migrations.AddField(
            model_name='slider',
            name='convocation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.convocationlist', verbose_name='ConvocationList'),
        ),
        migrations.AddField(
            model_name='slider',
            name='guest',
            field=models.CharField(default='', max_length=50, verbose_name='Guest Name'),
        ),
    ]
