# Generated by Django 3.1.7 on 2021-10-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211021_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=50, verbose_name='Degree')),
            ],
            options={
                'verbose_name': 'Degree',
                'verbose_name_plural': 'Degrees',
            },
        ),
        migrations.RenameModel(
            old_name='chart',
            new_name='ConvocationChart',
        ),
        migrations.RenameModel(
            old_name='Slider',
            new_name='HomeSlider',
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_usename', models.CharField(max_length=50, verbose_name='Degree')),
                ('s_id', models.IntegerField(unique=True, verbose_name='Student ID')),
                ('intake', models.IntegerField(verbose_name='Intake')),
                ('section', models.IntegerField(verbose_name='Section')),
                ('std_full_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('Cell_Phone', models.IntegerField(blank=True, default=0, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('paidFor', models.IntegerField(blank=True, default=0, verbose_name='Paid For Major')),
                ('totalPaid', models.IntegerField(blank=True, default=0, verbose_name='Paid For Major')),
                ('hasPaid', models.BooleanField(default=False, verbose_name='Payment Done')),
                ('regDate', models.DateField(auto_now=True, verbose_name='Registration Date')),
                ('totalMejor', models.ManyToManyField(to='api.Degree')),
            ],
            options={
                'verbose_name_plural': 'Registred Student',
            },
        ),
    ]
