# Generated by Django 3.2.8 on 2021-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211026_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isRegDone',
            field=models.BooleanField(default=False, verbose_name='Registration Done'),
        ),
    ]
