# Generated by Django 3.1.7 on 2021-10-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211030_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='tran_date',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Cell_Phone',
            field=models.CharField(default='', max_length=11, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='firstDegree_id',
            field=models.CharField(default='', max_length=11, verbose_name='First Degree ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='secondDegree_id',
            field=models.CharField(default='', max_length=11, verbose_name='Second Degree ID'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='stu_id1',
            field=models.CharField(default='', max_length=100, verbose_name='Student ID '),
        ),
        migrations.AlterField(
            model_name='registration',
            name='stu_name',
            field=models.CharField(default='', max_length=40, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='totalDegree',
            field=models.CharField(default='', max_length=5, verbose_name='Pay for Total Degree'),
        ),
    ]
