# Generated by Django 3.2.8 on 2021-10-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_student_tranid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tranId',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Transction ID'),
        ),
    ]
