# Generated by Django 3.2 on 2021-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hasPaid',
            field=models.BooleanField(default=False, verbose_name='Payment Done'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isRegDone',
            field=models.BooleanField(default=False, verbose_name='Registration Done'),
        ),
    ]
