# Generated by Django 3.1.7 on 2021-10-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211030_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='totalPaid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
