# Generated by Django 3.2.8 on 2021-10-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_student_tranid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
