# Generated by Django 3.2.8 on 2021-10-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transaction_tran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sid',
            field=models.IntegerField(default=0, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(max_length=15),
        ),
    ]
