# Generated by Django 3.2 on 2021-10-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211027_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Cell_Phone',
            field=models.IntegerField(default=0, verbose_name='Phone'),
        ),
    ]
