# Generated by Django 3.2.8 on 2021-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211026_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sid',
            field=models.IntegerField(default=0, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tran_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
